version: '2.4'
services: 
  bt:
    image: jangrui/baota:latest
    container_name: baota
    restart: unless-stopped
    user: root
    privileged: true
    hostname: ${HOSTNAME:-bt.cn}
    # network_mode: host
    # environment: 
      # SSH_PORT: 3322
    ulimits:
      nproc: 65535
      nofile:
        soft: 51200
        hard: 51200
    ports: 
      - 3322:3322
      - 8888:8888
    volumes: 
      - www:/www
      - ./www/backup:/www/backup
      
volumes: 
  www:
  